# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sciyen's site
email: r10921008@g.ntu.edu.tw
description: > # this means to ignore newlines until "baseurl:"
  A personal website of Yen Cheng Chu (sciyen) or 朱雁丞, who is a student
  studying in National Taiwan University (NTU) and majored in Electrical 
  Engineering (EE).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sciyen.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  sciyen

# Build settings
markdown: kramdown

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
